using System.Text;
using Jiper.FontAwesome.IconExtractor.Utilities;

namespace Jiper.FontAwesome.IconExtractor.CodeGeneration;

/// <summary>
/// Generates C# code for Font Awesome icon name constants without style prefixes.
/// </summary>
public static class IconNamesCodeGenerator
{
    /// <summary>
    /// Generates a C# class with icon name constants (without style prefixes) from a specific style.
    /// </summary>
    public static string GenerateIconNamesClass(string namespaceName, string className, List<IconInfo> icons)
    {
        var sb = new StringBuilder();

        AppendFileHeader(sb, namespaceName, className);
        AppendIconConstants(sb, icons);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendFileHeader(StringBuilder sb, string namespaceName, string className)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file was generated by Jiper.FontAwesome.IconExtractor");
        sb.AppendLine("// Source: https://github.com/FortAwesome/Font-Awesome");
        sb.AppendLine($"// Generated at: {DateTimeOffset.Now:O}");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public static class {IdentifierHelper.SanitizeTypeName(className)}");
        sb.AppendLine("{");
    }

    private static void AppendIconConstants(StringBuilder sb, List<IconInfo> icons)
    {
        var usedIdentifiers = new HashSet<string>(StringComparer.Ordinal);
        var iconNames = CollectIconNames(icons);

        foreach (var iconName in iconNames.OrderBy(n => n, StringComparer.Ordinal))
        {
            var identifier = IdentifierHelper.ToPascalCaseIdentifier(iconName);
            identifier = EnsureUniqueness(identifier, usedIdentifiers);

            // Only the icon name without style prefix (e.g., "arrow-right")
            sb.Append("    public const string ")
                .Append(identifier)
                .Append(" = \"")
                .Append(iconName)
                .AppendLine("\";");
        }
    }

    private static HashSet<string> CollectIconNames(List<IconInfo> icons)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);

        foreach (var icon in icons)
        {
            if (!string.IsNullOrWhiteSpace(icon.Name))
                names.Add(icon.Name);

            if (icon.Aliases != null)
            {
                foreach (var alias in icon.Aliases)
                {
                    if (!string.IsNullOrWhiteSpace(alias))
                        names.Add(alias);
                }
            }
        }

        return names;
    }

    private static string EnsureUniqueness(string identifier, HashSet<string> usedIdentifiers)
    {
        var baseId = identifier;
        var suffix = 1;

        while (!usedIdentifiers.Add(identifier))
        {
            identifier = $"{baseId}_{suffix++}";
        }

        return identifier;
    }
}
