using System.Text;
using Jiper.FontAwesome.IconExtractor.Utilities;

namespace Jiper.FontAwesome.IconExtractor.CodeGeneration;

/// <summary>
/// Generates C# code for Font Awesome icon constants.
/// </summary>
public static class IconCodeGenerator
{
    /// <summary>
    /// Generates a C# class with icon constants grouped by style.
    /// </summary>
    public static string GenerateClassByStyle(string namespaceName, string outerClassName,
        Dictionary<string, List<IconInfo>> iconsByStyle)
    {
        var sb = new StringBuilder();

        AppendFileHeader(sb, namespaceName, outerClassName);

        foreach (var kvp in iconsByStyle.OrderBy(k => IdentifierHelper.SanitizeTypeName(k.Key), StringComparer.Ordinal))
        {
            AppendStyleClass(sb, kvp.Key, kvp.Value);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendFileHeader(StringBuilder sb, string namespaceName, string outerClassName)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file was generated by Jiper.FontAwesome.IconExtractor");
        sb.AppendLine("// Source: https://github.com/FortAwesome/Font-Awesome");
        sb.AppendLine($"// Generated at: {DateTimeOffset.Now:O}");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public static partial class {IdentifierHelper.SanitizeTypeName(outerClassName)}");
        sb.AppendLine("{");
    }

    private static void AppendStyleClass(StringBuilder sb, string style, List<IconInfo> icons)
    {
        var styleClassName = IdentifierHelper.SanitizeTypeName(style);
        var stylePrefix = StylePrefixMapper.GetFaStylePrefix(style);

        sb.AppendLine($"    public static class {styleClassName}");
        sb.AppendLine("    {");

        var usedIdentifiers = new HashSet<string>(StringComparer.Ordinal);
        var iconNames = CollectIconNames(icons);

        foreach (var iconName in iconNames.OrderBy(n => n, StringComparer.Ordinal))
        {
            var identifier = IdentifierHelper.ToPascalCaseIdentifier(iconName);
            identifier = EnsureUniqueness(identifier, usedIdentifiers);

            // Include style prefix and the 'fa-' prefixed icon class (e.g., "fas fa-arrow-right")
            sb.Append("        public const string ")
                .Append(identifier)
                .Append(" = \"")
                .Append(stylePrefix)
                .Append(' ')
                .Append("fa-")
                .Append(iconName)
                .AppendLine("\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static HashSet<string> CollectIconNames(List<IconInfo> icons)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);

        foreach (var icon in icons)
        {
            if (!string.IsNullOrWhiteSpace(icon.Name))
                names.Add(icon.Name);

            if (icon.Aliases != null)
            {
                foreach (var alias in icon.Aliases)
                {
                    if (!string.IsNullOrWhiteSpace(alias))
                        names.Add(alias);
                }
            }
        }

        return names;
    }

    private static string EnsureUniqueness(string identifier, HashSet<string> usedIdentifiers)
    {
        var baseId = identifier;
        var suffix = 1;

        while (!usedIdentifiers.Add(identifier))
        {
            identifier = $"{baseId}_{suffix++}";
        }

        return identifier;
    }
}
